# PixelEssentials config
# MOTD and Welcome Message use MiniMessage: https://webui.advntr.dev/

motd:
  show-on-join: true
  message: "<gradient:#b0bec5:#eceff1>Welcome back, <gradient:#ff7e5f:#feb47b>{username}</gradient>!</gradient>\n<gradient:#b0bec5:#eceff1>It's currently <gradient:#ff7e5f:#feb47b>{server_time:h:mm a}</gradient> on <gradient:#ff7e5f:#feb47b>{server_time:M/d/y}</gradient>.</gradient>\n<gradient:#b0bec5:#eceff1>There are <gradient:#ff7e5f:#feb47b>{online}</gradient> players online.</gradient>"

messages:
  welcome-message:
    enabled: true
    message: "<light_purple>Welcome to the server {username}!</light_purple>"
  custom-join-message:
    enabled: true
    message: "<yellow>{username} joined the game</yellow>"
  custom-leave-message:
    enabled: true
    message: "<yellow>{username} left the game</yellow>"

teleportation:
  cooldown: 30
  delay: 5
  request-expiration: 30
  back-on-death-notification: true