# PixelEssentials config
# MOTD and Welcome Message use MiniMessage: https://webui.advntr.dev/

motd:
  show-on-join: true
  message: "<gradient:#b0bec5:#eceff1>Welcome back, <gradient:#ff7e5f:#feb47b>{username}</gradient>!</gradient>\n<gradient:#b0bec5:#eceff1>It's currently <gradient:#ff7e5f:#feb47b>{server_time_12}</gradient> on <gradient:#ff7e5f:#feb47b>{server_date_mdy}</gradient>.</gradient>\n<gradient:#b0bec5:#eceff1>There are <gradient:#ff7e5f:#feb47b>{online}</gradient> players online.</gradient>"

welcome-message:
  enabled: true
  message: "<light_purple>Welcome to the server {username}!</light_purple>"

teleportation:
  cooldown: 30
  delay: 5
  request-expiration: 30