# PixelEssentials config

welcome-message:
  enabled: true
  message: "<light_purple>Welcome to the server {username}!</light_purple>"

teleportation:
  cooldown: 30
  delay: 5
  request-expiration: 30