name: PixelEssentials
version: ${version}
author: kyleseven
description: A collection of essential features for your server.
main: me.kyleseven.pixelessentials.PixelEssentials
api-version: '26.2'
depend:
  - Vault
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.4.10
  - org.jooq:jooq:3.21.7
  - org.flywaydb:flyway-core:13.5.0
